version: "3.8"

services:
 ngnix:
  build:
   context: ./nginx
  container_name : "nginix_cont"
  ports:
   - "80:80"
  restart: always
  networks:
   - notes-app-nw
  healthcheck:
   test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
   interval: 30s
   timeout: 10s
   retries: 3
   start_period: 10s
  depends_on:
   - django_app
 
 django_app:
  build:
   context: . 
  container_name: "django_cont"
  ports:
   - "8000:8000"
  networks:
   - notes-app-nw
  command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
  depends_on:
   - db
  env_file:
   - ".env"
  healthcheck:
   test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
   interval: 30s
   timeout: 5s
   retries: 5
   start_period: 30s
  restart : always
 
 db:
  image : mysql
  container_name: "db_cont"
  healthcheck:
   test: ["CMD", "mysqladmin","ping", "-h","localhost", "-uroot","-proot"]
   interval: 10s
   timeout: 5s
   retries: 5
   start_period: 60s
  environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
  ports:
   - "3306:3306"
  networks:
   - notes-app-nw
  volumes :
   - mysql-data:/var/lib/mysql
   
volumes:
  mysql-data:
networks:
 notes-app-nw:







